# application-test.yml
spring:
  config:
    activate:
      on-profile: test
  application:
    name: aulaSpringUni-test
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///testdb?TC_TMPFS=/testtmpfs:rw
    username: postgres
    password: postgres
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect